[WIP] improve release process
CycloneDX/cyclonedx-python pull request #290
Opened 2021-12-26 11:38 UTC by jkowalleck

2022-01-15 13:08 UTC, jkowalleck commented
idea for the dockerfile: have setup in own venv. 
doenside: env under analysis will be the one we are running in. which is probably not the one a user wants to be analysed.

```
FROM python:3.10-slim-buster

ARG VERSION

RUN mkdir /cyclonedx-py

COPY ./dist /cyclonedx-py/dist

RUN python -m venv /cyclonedx-py/venv && \
    /cyclonedx-py/venv/bin/pip install cyclonedx-bom==${VERSION} --find-links file:///cyclonedx-py/dist

ENTRYPOINT ["/cyclonedx-py/venv/bin/cyclonedx-bom"]
```

2022-01-15 13:27 UTC, jkowalleck commented
@madpah i think i got the Docker release issue sorted out.

2022-01-17 16:43 UTC, madpah requested changes

2022-01-17 16:43 UTC, madpah commented on .github/workflows/docker.yml
> +      - name: Build own SBoM (JSON)
Should the JSON label not be XML?

2022-01-17 16:43 UTC, madpah commented on Dockerfile
> +ARG VERSIONARG VERSION
Typo?

2022-01-18 12:22 UTC, jkowalleck commented on .github/workflows/docker.yml
> +      - name: Build own SBoM (JSON)
yepp. fixed

2022-01-18 12:22 UTC, jkowalleck commented on Dockerfile
> +ARG VERSIONARG VERSION
yepp. fixed

2022-01-19 13:32 UTC, jkowalleck commented
fixed the findings.

2022-01-19 15:09 UTC, madpah approved these changes

2022-01-19 15:10 UTC, madpah commented
All good @jkowalleck - happy for this to be merged?

2022-01-20 08:22 UTC, merged