feat: add support for CycloneDX 1.4 specification
CycloneDX/cyclonedx-python pull request #294
Opened 2022-01-07 12:17 UTC by madpah

feat: add support for output to CycloneDX 1.4 (draft)
feat: Error with return code 2 if attempting to output in JSON and SchemaVersion < 1.2
test: Multiple tests added

Signed-off-by: Paul Horton <phorton@sonatype.com>

2022-01-07 12:54 UTC, madpah commented on tests/base.py
> +from lxml.etree import DocumentInvalid
@sonatype-lift ignore

2022-01-07 12:54 UTC, madpah commented on tests/base.py
> +            schema_validates = xml_schema.validate(etree.parse(io.BytesIO(bytes(bom_xml, 'ascii'))))
@sonatype-lift ignore

2022-01-07 12:58 UTC, madpah commented on tests/base.py
> +from lxml import etree
@sonatype-lift ignore

2022-01-07 12:58 UTC, madpah commented on tests/test_cyclonedx_json.py
> +import subprocess
@sonatype-lift ignore

2022-01-08 11:54 UTC, jkowalleck requested changes
i dont see why adding all the schema files to the project and doinng tests on JSON/XML is part of this project.

2022-01-08 11:54 UTC, jkowalleck commented on cyclonedx_py/client.py
> +        if str(self._arguments.output_format).upper() == 'JSON' and \
:heart_decoration:

2022-01-08 12:07 UTC, jkowalleck commented
@madpah  re https://github.com/CycloneDX/cyclonedx-python/pull/294#pullrequestreview-847148710
why add the JSON/XML/proto schema to the project? why ship it in the package?  

Dont see a reason why the files should be part of this package's tests, as they are part of [cyclonedx-python-lib](https://github.com/CycloneDX/cyclonedx-python-lib/tree/feat/schema-version-1.4/cyclonedx/schema) already. 
you could access the resources inside a package - via [importlib](https://docs.python.org/3.8/library/importlib.html?highlight=importlib#module-importlib.resources) or [pkg](https://setuptools.pypa.io/en/latest/pkg_resources.html#basic-resource-access)

2022-01-08 12:21 UTC, jkowalleck requested changes

2022-01-08 12:21 UTC, jkowalleck commented on tests/base.py
> +            self.assertTrue(True, 'JSON Schema Validation is not possible in Python < 3.7')
use unittest's `skipif` https://docs.python.org/3/library/unittest.html?highlight=skipif#unittest.skipIf
to skip tests. sont write conditional foo

2022-01-08 12:21 UTC, jkowalleck commented on tests/base.py
> +        self.assertTrue(schema_validates, 'Failed to validate Generated SBOM against XSD Schema')
```patch
-        if not schema_validates:
-            print(xml_schema.error_log.last_error)
-        self.assertTrue(schema_validates, 'Failed to validate Generated SBOM against XSD Schema')
+        self.assertTrue(schema_validates, 'Failed to validate Generated SBOM against XSD Schema\n'+xml_schema.error_log.last_error)
```

2022-01-08 12:21 UTC, jkowalleck commented on tests/base.py
> +        except DocumentInvalid as e:
whyyyyy? 
why catch the exception, if this exception is clearly a reason that this test would fail?

2022-01-10 08:34 UTC, madpah commented
@jkowalleck - fair point on the schema validation comments - will look at moving these (where required) back to `cyclonedx-python-lib`.

2022-01-10 11:33 UTC, madpah commented
> @madpah re [#294 (review)](https://github.com/CycloneDX/cyclonedx-python/pull/294#pullrequestreview-847148710) why add the JSON/XML/proto schema to the project? why ship it in the package?
> 
> Dont see a reason why the files should be part of this package's tests, as they are part of [`cyclonedx-python-lib`](https://github.com/CycloneDX/cyclonedx-python-lib/tree/feat/schema-version-1.4/cyclonedx/schema) already. you could access the resources inside a package - via [`importlib`](https://docs.python.org/3.8/library/importlib.html?highlight=importlib#module-importlib.resources) or [`pkg`](https://setuptools.pypa.io/en/latest/pkg_resources.html#basic-resource-access)
> 
> Saw the files are used in tests, to check output of `cyclonedx-python-lib` so why not add a `validate` capability to `cyclonedx-python-lib` ? it seams to be the perfect place.
> 
> ❌ what were the cons? why did you decide to put the data-validation in a downstream CLI tool instead of the library that generates the data in the first place?

Totally agree - have removed as covered in `cylonedx-python-lib`.

2022-01-13 09:21 UTC, merged