feat: make module callable
CycloneDX/cyclonedx-python pull request #326
Opened 2022-03-03 08:18 UTC by jkowalleck

fixes #321

2022-03-03 12:28 UTC, jkowalleck commented on tests/integration/test_can_call_module.py
> +                shell=False,
everything is fine.

2022-03-03 12:28 UTC, jkowalleck commented on tests/integration/test_can_call_module.py
> +import subprocess
ignore

2022-03-08 14:48 UTC, madpah requested changes
Hey @jkowalleck - like the idea. Thanks for the PR.

Can you also add a documentation update to explain this new invocation method as per #321 ?

Also - would we consider this a breaking change given PEP-3102 syntax has been added?

2022-03-08 15:38 UTC, jkowalleck commented
Sure, will add docs in the readme and other places.

Re: breaking change.
My intention was to add optional params to existing public api, so full backwards compatibility is given. Will check if I can improve the implementation.
Do you have any advice? Could you share your thoughts, @madpah ?

2022-03-08 17:52 UTC, jkowalleck commented
actually, i do not have any idea where i could document the all via `python -m`. Please point me to it, @madpah .

regarding "is this a breaking change?"
A: nope, it still adds **optional** parameters to existing methods. No issue with backwards-compatibility, as the functionality is optional and usage is self-contained.

2022-03-09 08:25 UTC, madpah commented
@jkowalleck - I've added Documentation to [CONTRIBUTING.md](https://github.com/CycloneDX/cyclonedx-python/blob/master/CONTRIBUTING.md) now - let me know if that is not enough to pop in some documentation changes.

Thanks on confirming NO breaking change 👍

2022-03-09 18:28 UTC, jkowalleck commented
Thanks, @madpah .
I still do not know where to document alternative call methods. 
I see https://github.com/CycloneDX/cyclonedx-python/blob/master/docs/usage.rst talking about the params and such. and is points out to call `cyclonedx-bom`. But where is the note that `cyclonedx-py` for example is an alternative call method? I would add the `python -m cyclonedx-py` at the exact same spot. 

Could you point me to the spot i could update, @madpah ? I can't see the forest for the trees.

2022-03-11 17:46 UTC, jkowalleck commented on docs/usage.rst
> -* :py:mod:`cyclonedx_py.parser.requirements.RequirementsFileParser`: Parses a file that you provide the path to that conforms to the ``requirements.txt`` :pep:`508` standard. It supports nested
fixed a warning from the sphinx parser, here.

2022-03-11 17:47 UTC, jkowalleck commented
added the missing docs. is this fine, @madpah  ?

2022-04-02 07:03 UTC, jkowalleck commented
@madpah  please have a look at the proposed changes of this PR

2022-04-05 06:28 UTC, madpah approved these changes

2022-04-05 06:28 UTC, merged