feat: Allow filtering for EnvironmentParser
CycloneDX/cyclonedx-python pull request #447
Opened 2022-11-30 11:47 UTC by tmeckel

This PR contains changes to the EnvironemtParser to allow the filtering of packages read from `pkg_resources.working_set`.

The  PR overlaps with #444 

As requested from `CONTRIBUTING.md`:

* commits are signed
* documentation added
* formatted with `isort` and `autopep8`
* added new tests for implemented functionality
* run tests locally successful with `poetry run tox`

2022-11-30 11:51 UTC, tmeckel commented on tests/test_parser_environment.py
> +            location_filter=["/tmp/fa12b66cac07e4bb480e98eba9627737"],
The path was intentionally chosen in the test case to achieve an empty result in the EnvironmentParser.

2022-11-30 11:52 UTC, tmeckel commented on tests/test_parser_environment.py
> +        parser_invalid_filter = EnvironmentParser(location_filter=["/tmp/fa12b66cac07e4bb480e98eba9627737"])
The path was intentionally chosen in the test case to achieve an empty result in the EnvironmentParser.

2022-12-01 08:46 UTC, jkowalleck commented on tests/test_parser_environment.py
> +        parser_invalid_filter = EnvironmentParser(location_filter=["/tmp/fa12b66cac07e4bb480e98eba9627737"])
will this work with windows? we will see when the CI tests are done

2022-12-01 08:46 UTC, jkowalleck commented on tests/test_parser_environment.py
> +            location_filter=["/tmp/fa12b66cac07e4bb480e98eba9627737"],
will this work with windows? we will see when the CI tests are done

2022-12-01 08:46 UTC, jkowalleck commented on docs/usage.rst
> +                            `requirements.txt` you wish to use, else we''ll look
note for myself -> need to check if this is correctly rendered to RTD

2022-12-01 08:47 UTC, jkowalleck commented
@tmeckel could you add the new CLI option to the <https://github.com/CycloneDX/cyclonedx-python#basic-usage> ?

2022-12-01 09:07 UTC, tmeckel commented
@jkowalleck I updated the `usage.rst` in starting at lines 34 and 62. Do you want me to add some more documentation?

2022-12-01 09:12 UTC, tmeckel commented
@jkowalleck will try to fix the failing test on Windows `test_parser_environment.py:72` as well.

```
Traceback (most recent call last):
  File "D:\a\cyclonedx-python\cyclonedx-python\tests\test_parser_environment.py", line 72, in test_simple_use_location_filter
    self.assertGreater(parser_sys_path.component_count(), 1)
AssertionError: 0 not greater than 1
```

2022-12-01 11:02 UTC, tmeckel commented
@jkowalleck  I pushed changes to add the requested additions to basic usage in `README.md` and fixed (hopefully) the failing test on Windows.

2022-12-01 18:40 UTC, jkowalleck commented on cyclonedx_py/parser/environment.py
> +        if os.name == 'nt' and location_filter:
node to self: need to double-check on that

2022-12-21 20:36 UTC, a1lu commented
Any progress on this? I would like to see this feature.

2022-12-22 00:08 UTC, jkowalleck commented
To move this forward, some git conflicts need to be sorted out first.
@tmeckel, could you look into this?

2022-12-22 08:26 UTC, jkowalleck requested changes

2022-12-22 08:26 UTC, jkowalleck commented on cyclonedx_py/client.py
> +                input_data_fh.close()
:x: 
`input_data_fh.close()` not needed, as it will happen automatically on exit of the `with` block

2022-12-22 08:26 UTC, jkowalleck commented on cyclonedx_py/client.py
> +            with input_data_fh:
what if `input_source` is None? will the `with` block crash?

2022-12-22 09:59 UTC, jkowalleck commented
@tmeckel @a1lu before putting more effort in this PR, 
please read https://github.com/CycloneDX/cyclonedx-python/issues/435#issuecomment-1362563367 

You will find good reasons why I will probably not merge this PR.
I see your solution working for your current use cases, but it appears to me not wholesome enough.

2022-12-22 09:59 UTC, closed without merging

2022-12-22 10:27 UTC, tmeckel commented
@jkowalleck I'm totally fine with your decision because in the meantime I fixed the issue that lead to this PR using a different approach.

2022-12-22 10:47 UTC, jkowalleck commented
@tmeckel re: https://github.com/CycloneDX/cyclonedx-python/pull/447#issuecomment-1362668417
I am happy to hear. 

Would you be so kind and open a new Q&A in https://github.com/CycloneDX/cyclonedx-python/discussions/categories/q-a 
where you describe the problem and answer your own "Question" with the solution you found?